# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ec58d346d47b96f9d253765c799b5c3996ef73444094363dbb7f12f821a196971f78b14280a8966d3f3c6aa9d649d1c59a2f1045124f24ba6b3cae7a5aa747

test:
  secret_key_base: 884137a8f5093d38a5c539506930db8458b259792e379fd90118663435f991ad828fae8890e9d11753b19e04eb8ff232c0cb38bdc6082aef0572ea11fa1c322c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
